RecuitmentApp/Controllers/FormCreatorController.cs
using RecuitmentApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RecuitmentApp.Controllers
{
    public class FormCreatorController : Controller
    {
        private MongoDAO daoObject = new MongoDAO();

        // GET: FormCreator
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult AddForm(FormDocumentModel form, string date)
        {
            RecruitmentModel recruitment = new RecruitmentModel();
            recruitment.formDocument = form;
            recruitment.EndDate = date;

            daoObject.InsertDocumentToCollection(recruitment, MongoDAO.RECRUITMENTS_COLLECTION);
            return View("IndexRecruitments", "RecruiterPanel");
        }
    }
}

RecuitmentApp/Controllers/RecruiterPanelController.cs
using MongoDB.Bson;
using MongoDB.Driver;
using RecuitmentApp.Models;
using RecuitmentApp.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RecuitmentApp.Controllers
{
    public class RecruiterPanelController : Controller
    {
        MongoDAO daoObject = new MongoDAO();
        // GET: RecruiterPanel
        [Authorize]
        public ActionResult IndexRecruitments()
        {
            return View();
        }

        [Authorize]
        public ActionResult EditRecruitment(string whichRecruitment)
        {
            ObjectId id = new ObjectId(whichRecruitment);
            var filter = Builders<RecruitmentModel>.Filter.Eq(r => r.Id, id);
            var recruitment = daoObject.GetRecruitment(filter);

            return View(recruitment);
        }

        [Authorize]
        [HttpPost]
        public ActionResult EditRecruitment(RecruitmentModel recruitment)
        {
            var filter = Builders<RecruitmentModel>.Filter.Eq(r => r.Id, recruitment.Id);
            RecruitmentModel rec = daoObject.GetRecruitment(filter);

            rec.IsOpen = recruitment.IsOpen;
            rec.EndDate = recruitment.EndDate;

            daoObject.UpdateRecruitment(rec);

            return View("IndexRecruitments");
        }

        [Authorize]
        public ActionResult Recruitment(string whichRecruitment)
        {
            ObjectId id = new ObjectId(whichRecruitment);
            var filter = Builders<RecruitmentModel>.Filter.Eq(r => r.Id, id);
            var recruitment = daoObject.GetRecruitment(filter);

            return View("Recruitment", recruitment);
        }

        [Authorize]
        public ActionResult CloseOpenRecruitment(string whichRecruitment, bool isOpen)
        {
            ObjectId id = new ObjectId(whichRecruitment);
            RecruitmentModel recruitment;

            var filter = Builders<RecruitmentModel>.Filter.Eq(r => r.Id, id);
            recruitment = daoObject.GetRecruitment(filter);
            recruitment.IsOpen = isOpen;
            daoObject.UpdateRecruitment(recruitment);

            return View("IndexRecruitments");
        }

        public ActionResult DeleteRecruitment(string whichRecruitment)
        {
            daoObject.DeleteRecruitment(whichRecruitment);

            return View("IndexRecruitments");
        }

        [Authorize]
        public ActionResult Applications(string whichRecruitment)
        {
            var filter = Builders<ApplicationModel>.Filter.Eq("RecruitmentId", whichRecruitment);

            List<ApplicationModel> applications = daoObject.GetApplications(filter);

            return Json(applications, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        public ActionResult ApplicationsIndex()
        {
            return View();
        }

        [Authorize]
        public ActionResult ApplicationDetails(string whichApplication)
        {
            ViewBag.whichApp = whichApplication;

            return View();
        }

        [Authorize]
        public ActionResult JsonApplication(string whichApplication)
        {
            ObjectId id = new ObjectId(whichApplication);
            var filter = Builders<ApplicationModel>.Filter.Eq(r => r.Id, id);

            var applications = daoObject.GetApplications(filter);

            return Json(applications.First(), JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        public ActionResult AcceptApplication(string whichApplication)
        {
            ObjectId id = new ObjectId(whichApplication);
            var filter = Builders<ApplicationModel>.Filter.Eq(r => r.Id, id);

            var application = daoObject.GetApplications(filter);

            SendingEmail se = new SendingEmail();

            se.SendEmail(application.First().Email, SendingEmail._ACCEPT_APPLICATION_SUBJECT);

            daoObject.AcceptDeclineApplication(whichApplication, true);

            return View("ApplicationsIndex");
        }

        [Authorize]
        public ActionResult DenyApplication(string whichApplication)
        {
            ObjectId id = new ObjectId(whichApplication);
            var filter = Builders<ApplicationModel>.Filter.Eq(r => r.Id, id);

            var application = daoObject.GetApplications(filter);

            SendingEmail se = new SendingEmail();

            se.SendEmail(application.First().Email, SendingEmail._REJECT_APPLICATION_SUBJECT);

            daoObject.AcceptDeclineApplication(whichApplication, false);

            return View("ApplicationsIndex");
        }
    }
}

RecuitmentApp/Controllers/RecruitmentsController.cs
using MongoDB.Bson;
using MongoDB.Driver;
using RecuitmentApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RecuitmentApp.Controllers
{
    public class RecruitmentsController : Controller
    {
        private MongoDAO daoObject = new MongoDAO();
        // GET: Recruitments
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Recruitment(string whichRecruitment)
        {
            ObjectId id = new ObjectId(whichRecruitment);
            var filter = Builders<RecruitmentModel>.Filter.Eq(r => r.Id, id);
            var recruitment = daoObject.GetRecruitment(filter);

            return View("Recruitment", recruitment);
        }

        public ActionResult Recruitments()  // funkcja do wywolania z js
        {
            List<RecruitmentModel> listaRekrutacji = daoObject.GetAllRecruitments();

            return Json(listaRekrutacji, JsonRequestBehavior.AllowGet);
        }
    }
}

RecuitmentApp/Views/RecruiterPanel/ApplicationDetails.cshtml
<body>
    <link rel="stylesheet" href="~/Content/Styles/RecruitmentStyle.css" />

    <div id="root" data-param="@ViewBag.whichApp">
    </div>

    <script src="~/Scripts/jsx/ApplicationDetails.jsx"></script>
</body>

RecuitmentApp/Views/RecruiterPanel/ApplicationsIndex.cshtml
<body>
    <script src="~/Scripts/JQuery/Utils.js"></script>

    <input type="text" placeholder="Wyszukaj zgłoszenia" onkeyup="filterAppliactions(this)" style="margin:5px 0px;" />

    <div id="root">
    </div>

    <script src="~/Scripts/jsx/ApplicationsIndex.jsx"></script>
</body>

RecuitmentApp/Views/RecruiterPanel/EditRecruitment.cshtml
@model RecuitmentApp.Models.RecruitmentModel

@{
    ViewBag.Title = "EditRecruitment";
}

<h2>@Model.formDocument.Tytul</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RecruitmentModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div>
            @Html.HiddenFor(model => model.Id)
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsOpen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsOpen)
                    @Html.ValidationMessageFor(model => model.IsOpen, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input class="form-control" id="EndDate" name="EndDate" type="date" value="" />
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zapisz" class="btn btn-default" />
                <br/>
                @Html.ActionLink("Usuń rekrutację", "DeleteRecruitment", new { whichRecruitment = Model.Id }, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Wróć", "IndexRecruitments")
</div>

RecuitmentApp/Views/RecruiterPanel/IndexRecruitments.cshtml
<body>
    <script src="~/Scripts/JQuery/Utils.js" ></script>
    <link rel="stylesheet" href="~/Content/Styles/SelectionStyle.css" />

    <div>
        <div>
            <input type="button" value="Dodaj rekrutację" onclick="location.href='@Url.Action("Index", "FormCreator")'">
            <input type="text" placeholder="Wyszukaj rekrutacje" onkeyup="filterAdminRecruitments(this)" style="margin:5px 0px;"/>
            <div className="select">
                <select onchange="filterRecruitmentActive(this)">
                    <option value=0>-Filtruj aktywne-</option>
                    <option value="active">Aktywne</option>
                    <option value="inactive">Nieaktywne</option>
                </select>
                <div className="select__arrow"></div>
            </div>
        </div>
        <div id="root">

        </div>
    </div>

    @*<script src="~/Scripts/jsx/ReactElement.jsx"></script>*@
    <script src="~/Scripts/jsx/RecruiterJSX/RecruitmentsListWithEdits.jsx"></script>
    <script src="~/Scripts/jsx/RecruitmentsBox.jsx"></script>
</body>

RecuitmentApp/Views/RecruiterPanel/Recruitment.cshtml
@model RecuitmentApp.Models.RecruitmentModel

<link rel="stylesheet" href="~/Content/Styles/RecruitmentStyle.css" />

<div id="bbb">
    <h1>@Model.formDocument.Tytul</h1>
    <div id="small-stuff">
        <div id="dataKonca" class="box-small">
            <h2>Data końca</h2>
            @Model.EndDate
        </div>

        <div id="opisZarobkow" class="box-small">
            <h2>Proponowane zarobki</h2>
            @Model.formDocument.Zarobki
        </div>
    </div>

        <div id="opisRekrutacji" class="box">
            <h2>Opis stanowiska</h2>
            @Model.formDocument.Opis
        </div>

        <div id="opisWymagan" class="box">
            <h2>Wymagania</h2>
            @Model.formDocument.Wymagania
        </div>

        <div id="opisOferty" class="box">
            <h2>Oferujemy</h2>
            @Model.formDocument.Oferujemy
        </div>

        <input type="button" value="Edytuj" onclick="location.href='@Url.Action("EditRecruitment", "RecruiterPanel", new { whichRecruitment = @Model.Id })'" />
        @if (Model.IsOpen)
        {
            <input type="button" value="Zakończ rekrutację" onclick="location.href='@Url.Action("CloseOpenRecruitment", "RecruiterPanel", new { whichRecruitment = @Model.Id, isOpen = false})'" />
        }
        else
        {
            <input type="button" value="Aktywuj rekrutację" onclick="location.href='@Url.Action("CloseOpenRecruitment", "RecruiterPanel", new { whichRecruitment = @Model.Id, isOpen = true})'" />
        }
    </div>